site_name: CSMT Documentation
site_url: https://paolino.github.io/csmt/
repo_url: https://github.com/paolino/csmt

theme:
  name: mkdocs
  color_mode: auto
  user_color_mode_toggle: true

plugins:
  - search
  - asciinema-player

markdown_extensions:
  - callouts
