services:
  csmt-proxy:
    image: ghcr.io/paolino/csmt/csmt-proxy:latest
    container_name: csmt-proxy
    restart: unless-stopped
    secrets:
      - source: csmt-proxy-config
        target: /config.yaml
    labels:
      - traefik.docker.network=web
      - traefik.http.routers.csmt-proxy.rule=(Host(`csmt-proxy.plutimus.com`))
      - traefik.http.routers.csmt-proxy.tls=true
      - traefik.http.services.csmt-proxy.loadbalancer.server.port=8080
      - traefik.http.routers.csmt-proxy.tls.certresolver=le
    networks:
      - web
  csmt-source:
    image: ghcr.io/paolino/csmt/csmt-source:latest
    container_name: csmt-source
    restart: unless-stopped
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
    secrets:
      - source: csmt-plutimus-config
        target: /config.yaml
    depends_on:
      - csmt-proxy

secrets:
  csmt-proxy-config:
    file: ../tmp/proxy.yaml
  csmt-plutimus-config:
    file: ../tmp/plutimus.yaml

networks:
  web:
    external: true